TZ 11
v01cecrack/java-filmorate pull request #4
Opened 2023-05-28 12:51 UTC by v01cecrack

2023-05-29 17:02 UTC, NikolaiDem requested changes

2023-05-29 17:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        } catch (Exception e) {
Лучше перехватывать ожидаемое (более специфическое) исключение

2023-05-30 01:05 UTC, v01cecrack commented
Я обязательно вернусь к этому проекту летом и справлю все недочеты, просто сейчас у меня сессия и очень мало времени

2023-05-30 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    private final FilmService filmService;
Не исправлено

2023-05-30 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setMpaGenreLikesForFilm(Film film, Set<RatingMpa> mpaList, List<Genre> genres,
Не исправлено

2023-05-30 15:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            } catch (Exception e) {
Не исправлено

2023-05-30 15:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                if (friendShip.getUserId() == userId) {
Не исправлено

2023-05-30 15:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            users.add(userStorage.findUserById(commonFriendId));
Не исправлено

2023-05-30 15:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            var user = userStorage.findUserById(friendId);
Не исправлено

2023-05-30 15:24 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationFilmService.java
>  public class ValidationFilmService {
Не исправлено

2023-05-30 15:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FriendshipDbStorage.java
> +        } catch (Exception e) {
Не исправлено

2023-05-30 15:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        } catch (Exception e) {
Не исправлено

2023-05-30 19:24 UTC, v01cecrack commented
Вроде исправил, что нужно, просто я думал, там где написано "лучше" означает, что это рекомендация.

2023-05-31 07:20 UTC, NikolaiDem approved these changes

2023-06-04 19:11 UTC, merged